### PR TITLE
Ignore case for http(s) scheme

### LINKED ISSUE #1990: NetworkRequestHandler cannot handle uppercased HTTP or HTTPS schemes
I'm getting a `BitmapHunter Exception - Unrecognized type of request` even though everything seems fine, as stated in the title, somehow my URL ended up using **HTTP** (UPPERCASE) and here:

https://github.com/square/picasso/blob/6f3189fb94f0c1a647a5ada605c505e00caf51f5/picasso/src/main/java/com/squareup/picasso3/NetworkRequestHandler.java#L46-L52

Is my (and possible others) problem, i don't know if it's intended to NOT support the UPPERCASE case scheme, but using `(SCHEME_HTTP.equalsIgnoreCase(scheme) || SCHEME_HTTPS.equalsIgnoreCase(scheme))` would solve the problem.

Also, this is a silly mistake that is not easy to find, if the insensitive case is intended, at least put some good exception message..

### PR DESCRIPTION
**Pull request by Grohden**
Could not use [normalizeScheme](https://developer.android.com/reference/android/net/Uri.html#normalizeScheme()) due to api level

### CODE REVIEW

**Comment by Grohden** [comment]
@JakeWharton you are right! also, i'm wondering if only **allowing** network request handler to handle this would solve. I will write tests today

**Comment by Grohden** [comment]
@JakeWharton I wrote the tests (i don't know if they are in following the conventions.. also, this is my first test) and i also tested the sample app with the schema in uppercase, everything loaded correctly.

File: picasso/src/test/java/com/squareup/picasso3/NetworkRequestHandlerTest.java [hunk 1]
```diff
@@ -203,6 +204,26 @@
...
+            "https",
+            "HTTP",
+            "HTTPS",
+            "HTtP",
+    };
+
+    for (String scheme : schemes) {
+      final Uri uri = URI_1.buildUpon().scheme(scheme).build();
+      final Boolean shouldHandle = networkHandler.canHandleRequest(
+              TestUtils.mockRequest(uri)
```
Comment (NightlyNexus) [inline picasso/src/test/java/com/squareup/picasso3/NetworkRequestHandlerTest.java]: i'd inline the `mockRequest` for tests, but i'm hardly opinionated here.

Comment (Grohden) [reply picasso/src/test/java/com/squareup/picasso3/NetworkRequestHandlerTest.java]: I didn't inline because i would need to import the whole package there, from picasso instead of okhttp.. :/

File: picasso/src/test/java/com/squareup/picasso3/NetworkRequestHandlerTest.java [hunk 2]
```diff
@@ -203,6 +204,26 @@
...
+    String[] schemes = {
+            "http",
+            "https",
+            "HTTP",
+            "HTTPS",
+            "HTtP",
+    };
+
+    for (String scheme : schemes) {
+      final Uri uri = URI_1.buildUpon().scheme(scheme).build();
```
Comment (jrodbx) [inline picasso/src/test/java/com/squareup/picasso3/NetworkRequestHandlerTest.java]: nit: remove final

File: picasso/src/test/java/com/squareup/picasso3/NetworkRequestHandlerTest.java [hunk 3]
```diff
@@ -203,6 +204,26 @@
...
+      final Boolean shouldHandle = networkHandler.canHandleRequest(
```
Comment (jrodbx) [inline picasso/src/test/java/com/squareup/picasso3/NetworkRequestHandlerTest.java]: no final, boolean

File: picasso/src/test/java/com/squareup/picasso3/NetworkRequestHandlerTest.java [hunk 4]
```diff
@@ -203,6 +204,26 @@
...
+              TestUtils.mockRequest(uri)
+      );
+
+      assertThat(shouldHandle).isTrue();
```
Comment (jrodbx) [inline picasso/src/test/java/com/squareup/picasso3/NetworkRequestHandlerTest.java]: can probably inline here.

**Comment by jrodbx** [comment]
Fixes #1990

File: picasso/src/test/java/com/squareup/picasso3/NetworkRequestHandlerTest.java (hunk 4 above)
Comment (Grohden) [reply picasso/src/test/java/com/squareup/picasso3/NetworkRequestHandlerTest.java]: i didn't inline here for legibility and column limit (that's why i used final btw, i always think that the compiler will inline "one reference/usage final" variables - but i know that even without `final` the compiler can do that), anyway, i will inline it
