### PR TITLE
Wrap Source to prevent propagating bad Bitmaps.

### LINKED ISSUE #1998: Use exception-catching Source wrapper to prevent propagating bad Bitmaps
Sometimes Bitmap.decodeStream doesn't throw when the underlying stream does. This is unequivocally an Android bug. However, we can trivially detect this case by wrapping the source, marking any exceptions that are thrown, and re-throwing if the method erroneously returns normally.

### PR DESCRIPTION
**Pull request by NightlyNexus**
Closes #1998

### CODE REVIEW

File: picasso/src/main/java/com/squareup/picasso3/BitmapUtils.java [hunk 1]
```diff
@@ -196,6 +199,29 @@ static boolean isXmlResource(Resources resources, @DrawableRes int drawableId) {
...
+    IOException thrownException;
+
+    ExceptionCatchingSource(Source delegate) {
+      super(delegate);
+    }
+
+    @Override public long read(Buffer sink, long byteCount) throws IOException {
+      try {
+        return super.read(sink, byteCount);
+      } catch (IOException e) {
```
Comment (NightlyNexus) [inline picasso/src/main/java/com/squareup/picasso3/BitmapUtils.java]: i'm assuming BitmapFactory.decodeStream doesn't swallow other throwables...

**Comment by NightlyNexus** [comment]
It'd be nice to log or something when this happens. I'd like to know how often and on what devices this happens.

**Comment by JakeWharton** [comment]
Sure. Add it!

File: picasso/src/main/java/com/squareup/picasso3/BitmapUtils.java [hunk 2]
```diff
@@ -93,14 +95,12 @@ static void calculateInSampleSize(int reqWidth, int reqHeight, int width, int he
    * about the supplied request in order to do the decoding efficiently (such as through leveraging
    * {@code inSampleSize}).
    */
-  static Bitmap decodeStream(Source source, Request request) throws IOException {
-    BufferedSource bufferedSource = Okio.buffer(source);
-
+  static Bitmap decodeStream(BufferedSource source, Request request) throws IOException {
```
Comment (JakeWharton) [inline picasso/src/main/java/com/squareup/picasso3/BitmapUtils.java]: Why did you make this change? Since we're using a Source to wrap the incoming source it makes this buffering layer mostly useless. Why not wrap the underlying Source as close as possible to the original before applying any buffering layer?

**Comment by NightlyNexus** [comment]
yep, agree on both comments. will return!

**Comment by JakeWharton** [comment]
Thanks!
